Login:
  UsesLogin: false
  Username: ""
  Password: ""
Connection:
  Host: "localhost"
  GamePort: 8084
  RelayPort: 4000
  AutoConnect: true
  ConnectionCheckInterval: 120
  TimeoutLength: 2
Database:
  Local: True
  DB: "db.db"
  Storage: "storage"
  Crafting: "crafting"
  Craftables: "craftables"
  Power: "power"
  Requests: "requests"
  Host: "localhost"
  Username: ""
  Password: ""
GUI:
  MaxPowerLen: 500
  StartWidth: 800
  StartHeight: 600
Crafting: 
  CalculateProcessingRequirements: true
  StorePastCraftingRequests: true
  Queue:
    PushingStopsCurrentRequest: true
    AllowOverloadingRequests: true
Storage:
  UpdateIntervalInMinutes: 15
Power:
  UpdateFrequency: 2500
  EmergencyLevel: 1_000_000
  ConvertFuelsToEU: true
Emergency:
  EmergencyAlerts: true
  DiscordContacts:
    - ". discord username"
  DiscordToken: ""
  DiscordUseEmbeddedMessages: true
Robots:
  Enabled: false
Debug:
  VerboseLevel: 3
  OfflineMode: false
